### ISSUE TITLE
File not found when using a baseurl

### ISSUE THREAD

**Issue by redtide** [adobe/hyde-theme#2]
### Expected Behaviour
Jekyll should not report missing files

### Actual Behaviour
Jekyll reports "ERROR `/assets/scripts/indices.js' not found." while running

### Reproduce Scenario (including but not limited to)
Use a baseurl for the website

#### Steps to Reproduce
access a page and/or press F5

#### Platform and Version
Arch Linux (5.7.12-arch1-1)
Jekyll 3.9.0
ruby 2.5.3p105 (installed via RVM to match the version used by previous GH Pages Jekyll version 3.8.5)

#### Logs taken while reproducing problem
see Actual Behavior

**Comment by redtide** [comment]
it seems the issue can be fixed by replacing [_includes/head.html#L21](https://github.com/adobe/hyde-theme/blob/master/_includes/head.html#L21) with
```html
<script src="{{ '/assets/scripts/indices.js' | relative_url }}"></script>
```

Extra:
1. I noticed there is another place to fix a link with a missing `relative_url`, in [indices.js](https://github.com/adobe/hyde-theme/blob/master/assets/scripts/indices.js#L30).
2. For some strange reason this javascript doesn't work in the website I'm going to install the theme, but it does in the stlab one.
It works by adding `layout: null` in the front matter.

Let me know if you want a pull request to fix all the above.

**Comment by sean-parent** [comment]
Thank you for this report. A PR would be much appreciated. I will try and hunt down the hard dependency on the layout property in the front matter.

**Comment by redtide** [comment]
it is already used in the stlab [feed.xml](https://github.com/stlab/stlab.github.io/blob/master/feed.xml#L2) and it's documented [here](https://jekyllrb.com/docs/front-matter/#predefined-global-variables). It is used in non html files to use Liquid without having Jekill to parse it as an html page.
