### ISSUE TITLE
Limited customization

### ISSUE THREAD

**Issue by redtide** [adobe/hyde-theme#3]
### Expected Behaviour
Currently, customizing with the override sass files is limited to a portion of the style.
It seems not possible to customize the syntax highlighting for the normal page's content and not working at all for the code in the tables of the generated pages.
As a side note I wonder why this theme wasn't made as a simple "add-on" instead, which forces an user to use it for the entire website instead using it only for the generated code documentation.

### Actual Behaviour
It is possible to customize the syntax highlighting only by including and modifying the original `main-{light|dark}.scss` files.

### Reproduce Scenario (including but not limited to)
N/A

#### Steps to Reproduce
N/A

#### Platform and Version
Not relevant.

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by sean-parent** [comment]
You can override the theme following the [Jekyll instructions here](https://jekyllrb.com/docs/themes/#overriding-theme-defaults). I would be interested in a better/more supported solution. At the moment, the theme was scraped out of a couple of sites we built with Jekyll, and @fosterbrereton was kind enough to add some direct support for customization.

**Comment by redtide** [comment]
That is what I did ([here](https://redtide.github.io/artist/)), but I thought it would be easier maybe by moving the [overrides import](https://github.com/adobe/hyde-theme/blob/master/assets/css/main-light.scss#L38) at the end of the file to avoid to copy the entire scss (which makes a bit useless the overrides purpose). I'll try something later.
